spring:
  profiles :
    group :
      development : common, common-local, local
      quality-assurance : common, common-qas, qas
      production : common, common-prd, prd

server:
  port: 8071

logging:
  charset:
    file: UTF-8
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
    file: "%d{yyyy-MM-dd HH:mm:ss} [%-3level] %logger - %msg %n"
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 100MB
      total-size-cap: 10GB
      file-name-pattern: "%d{yyyy-MM-dd}.%i.gz" #날짜별 아카이브파일 생성

local :
  local :
    key : application
  key : applicationKey