spring:
  profiles :
    group :
      development : common, common-local, local
      quality-assurance : common, common-qas, qas
      production : common, common-prd, prd
server:
  port: 8071
local :
  local :
    key : application
  key : applicationKey