logging:
  charset:
    console: UTF-8
    file: UTF-8
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
    console: "%yellow([%d{${logging.pattern.dateformat}}]) %magenta([%-3level]) %cyan(%logger) - %msg %n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%-3level] %logger - %msg %n"
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 1MB
      total-size-cap: 10GB
      file-name-pattern: "%d{yyyy-MM-dd}.%i.gz" #날짜별 아카이브파일 생성