spring:
  profiles :
    group :
      development : common, common-local, local
      quality-assurance : common, common-qas, qas
      production : common, common-prd, prd
server:
  port: 8070
logging:
  charset:
    file: UTF-8
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
    file: "%d{yyyy-MM-dd HH:mm:ss} [%-3level] %logger - %msg %n"
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 100MB
      total-size-cap: 10GB
      file-name-pattern: "%d{yyyy-MM-dd}.%i.gz" #날짜별 아카이브파일 생성
# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: com.woongjin.pjt.wsurveyapi
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: / #  Swagger UI 경로 => localhost:8070/  (defaults : swagger-ui/index.html)
    tags-sorter: alpha # alpha: 알파벳 순 태그 정렬
    operations-sorter: alpha
    enabled: true
    display-operation-id: true
    display-request-duration: true
  api-docs:
    path: /api-docs #  api-docs 경로 => localhost:8070/api-docs
    groups:
      enabled: true
  cache:
    disabled: true


